// Define a variable to hold the total number of levels generated
let totalLevelsGenerated = 0;

// Function to update the total levels generated
function updateTotalLevelsGenerated() {
    // Calculate the total levels generated by summing up the length of each level data array
    totalLevelsGenerated = levelData_mineshaft.length + levelData_elevator.length + levelData_warehouse.length;
}

// Function to display the total levels generated
function displayTotalLevelsGenerated() {
    // Find the element where the total levels will be displayed
    let statsOutputDiv = document.getElementById('statsOutput');

    // Create a paragraph element to display the total levels
    let statsParagraph = document.createElement('p');
    statsParagraph.textContent = `Total Levels Generated: ${totalLevelsGenerated}`;

    // Append the paragraph element to the stats output div
    statsOutputDiv.appendChild(statsParagraph);
}

// Call the update function initially to set the initial total levels generated
updateTotalLevelsGenerated();

// Call the display function to show the total levels generated on the stats tab
displayTotalLevelsGenerated();
